spring:
  datasource:
    username: ${USERNAME:user99}
    password: ${PASSWORD:fSOm1clIpxWiuHbL8QS3XHCnmOYiMQQo}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
  jpa:
    hibernate:
      ddl-auto: validate