---
logging:
  level:
    root: WARN
    org:
      springframework:
        security: trace

sentry:
  dsn: https://4134972a1845e5ee2f0cb1f116324b16@o4508176732061696.ingest.de.sentry.io/4508176775577680

springdoc:
  api-docs:
    path: /api-docs
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: production
  application:
    name: app

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0
