spring:
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    sql:
      init:
        mode: never
  datasource:
    password: fSOm1clIpxWiuHbL8QS3XHCnmOYiMQQo
    url: jdbc:postgresql://dpg-csd4m13v2p9s73fsfd80-a:5432/database99_bhrr
    username: user99